more documentation lmao

diff --git a/puppet3 b/puppet3
--- a/puppet3
+++ b/puppet3
@@ -103,9 +103,9 @@ require_non_empty () {
 }
 
 dir_target () {
-    # Hacky way to resolve a symbolic link if it's a directory. Used
-    # because readlink is not specified in 2008 POSIX, though note
-    # that it does exist in later publications.
+    # Hacky way to resolve a symbolic link if it's pointing to a
+    # directory. Used because readlink is not specified in 2008 POSIX,
+    # though note that it does exist in later publications.
     #
     # Use a subshell just to prevent changing the current directory of
     # the calling shell.
@@ -295,6 +295,8 @@ bring_online () {
 promote_fallback () {
     _new_main_dir="$1"
 
+    # Switch between xxx_1 and xxx_2, as appropriate, based on the
+    # value of $1.
     case "$_new_main_dir" in
         "$server_dir_1")
             _main_id="1"
@@ -331,7 +333,7 @@ promote_fallback () {
     "$fallback_status_pipe_link" && \
     ln -sf -- "$_new_main_log_pipe" "$main_log_pipe_link" && \
     ln -sf -- "$_new_fallback_log_pipe" "$fallback_log_pipe_link"
-    ) || die "couldn't create symlink(s)"
+    ) || die "couldn't update symlink(s)"
 }
 
 require_code () {
@@ -475,10 +477,6 @@ esac
 umask 077
 
 if [ "$1" = "setup" ]; then
-    # Setup requires user input and so shouldn't be run
-    # non-interactively.
-    [ -t 0 ] || die "setup must be run interactively"
-
     # Search the current directory for files that shouldn't be there.
     # This is more of a sanity check than anything, to make sure the
     # user doesn't accidentally clobber an already-populated
@@ -513,33 +511,37 @@ if [ "$1" = "setup" ]; then
         . "$conf_file" || die "couldn't source $conf_file"
     fi
 
-    # Fill in any missing configuration entries as needed. These
-    # aren't validated, but the user can always manually edit
-    # puppet.conf; generating the config like this is mostly a matter
-    # of convenience.
-    #
-    # Note that $conf_file is allowed to exist, and may already be
-    # populated with values. We'll recreate that file, but the old
-    # values of $src_repo, $src_branch, $conf_repo, and
-    # $conf_branch will be preserved.
-    if [ -z "$src_repo" ]; then
-        printf "Enter the code repository: "
-        read -r src_repo
-    fi
+    # Only ask for configuration settings if we're in an interactive
+    # terminal.
+    if [ -t 0 ]; then
+        # Fill in any missing configuration entries as needed. These
+        # aren't validated, but the user can always manually edit
+        # puppet.conf; generating the config like this is mostly a
+        # matter of convenience.
+        #
+        # Note that $conf_file is allowed to exist, and may already be
+        # populated with values. We'll recreate that file, but the old
+        # values of $src_repo, $src_branch, $conf_repo, and
+        # $conf_branch will be preserved.
+        if [ -z "$src_repo" ]; then
+            printf "Enter the code repository: "
+            read -r src_repo
+        fi
 
-    if [ -z "$src_branch" ]; then
-        printf "Enter the code branch: "
-        read -r src_branch
-    fi
+        if [ -z "$src_branch" ]; then
+            printf "Enter the code branch: "
+            read -r src_branch
+        fi
 
-    if [ -z "$config_repo" ]; then
-        printf "Enter the config repository: "
-        read -r config_repo
-    fi
+        if [ -z "$config_repo" ]; then
+            printf "Enter the config repository: "
+            read -r config_repo
+        fi
 
-    if [ -z "$config_branch" ]; then
-        printf "Enter the config branch: "
-        read -r config_branch
+        if [ -z "$config_branch" ]; then
+            printf "Enter the config branch: "
+            read -r config_branch
+        fi
     fi
 
     # Make all necessary directories.
@@ -550,10 +552,13 @@ if [ "$1" = "setup" ]; then
     "$server_2_unique_dir" \
     "$common_dir" || die "couldn't make required directories"
 
-    # Set up the named pipes we use for IPC.
+    # Set up the named pipes we use for IPC. We don't create
+    # $log_pipe_1 or $log_pipe_2 on purpose, because those files are
+    # generated by the wrapper script (though we do set up links to
+    # those below).
     mkfifo -m 600 -- "$status_pipe_1" "$status_pipe_2"
 
-    # Set up the initial symlinks
+    # Set up the initial symlinks.
     (
     ln -s -- "$server_dir_1" "$main_link" && \
     ln -s -- "$server_dir_2" "$fallback_link" && \
@@ -565,8 +570,9 @@ if [ "$1" = "setup" ]; then
     ln -s -- "$log_pipe_2" "$fallback_log_pipe_link"
     ) || die "couldn't create symlink(s)"
 
-    # Generate the config file based on the user's choices. Will have
-    # rw------- perms, as per 'umask' above.
+    # Generate the config file, maybe taking the user's prior input
+    # into account (if this was called in an interactive terminal),
+    # or the prior contents (which won't be overwritten).
     printf "%s" "#!/bin/false
 src_repo=$( quote "$src_repo" )
 src_branch=$( quote "$src_branch" )
@@ -621,7 +627,6 @@ case \"\$2\" in
     *) exit 1 ;;
 esac
 
-# Files we create should also be rw-------
 umask 077
 
 server_dir=\"\$puppet_dir/server_\$2\"
@@ -808,13 +813,15 @@ require_non_empty "$config_repo"
 require_non_empty "$config_branch"
 
 # Initialize both tmux servers appropriately, as we will likely need
-# to be able to connect to them.
+# to be able to connect to them. This won't create new windows or
+# servers unless necessary.
 tmux_init "$socket_file_1"
 tmux_init "$socket_file_2"
 
 # Some commands are "exclusive" and shouldn't be run concurrently.
 # Others aren't. Handle the commands that don't care about being run
-# "simultaneously" first.
+# "simultaneously" first, but still need access to e.g. the tmux
+# window(s).
 case "$1" in
     "main")
         tmux_attach "$main_socket_link"
@@ -830,6 +837,12 @@ esac
 # The rest of the script should be "exclusive"; it should not be run
 # concurrently in the same directory. Scripts in different
 # directories may run concurrently.
+#
+# This works because in typical cases, 'mkdir' is atomic, and the
+# call will fail if the directory already exists. Note that this is
+# not REQUIRED to be atomic by POSIX, though, so it is not foolproof,
+# but practically it will work well enough, and better alternatives
+# that maintain portability do not appear available.
 mkdir -- "$lock_dir" ||
 die "an instance of this script is already running"
 
@@ -842,6 +855,8 @@ exit_hook () {
     return "$_old_exit_code"
 }
 
+# Trap every signal we care about. All of these will cause us to exit,
+# after performing cleanup actions (removing our lock directory).
 trap 'trap - 0; exit_hook; exit' EXIT HUP INT QUIT ABRT TERM
 
 case "$1" in
@@ -925,10 +940,12 @@ fi
 # Main is running; fallback isn't. We need to bring up fallback, and
 # shut down main in an orderly fashion.
 if [ "$_main_alive" -eq 0 ] && [ "$_fallback_alive" -ne 0 ]; then
+    # Turn on fallback. Main is still running at this point.
     bring_online "$_fallback_dir" \
     "$fallback_socket_link" \
     "$fallback_status_pipe_link"
 
+    # Wait for main to go offline.
     bring_offline "$main_socket_link" "$main_log_pipe_link"
 
     # Everything went well; promote the fallback instance to the main
